apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx  
  name: webserver
  namespace: schulung
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      serviceAccount: webserver
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
        - name: nginx-index-file
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: nginx-index-file
        configMap:
          name: indexhtml

