apiVersion: v1
data:
  index.html: |-
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a configmap Index file </h1>
    </html
kind: ConfigMap
metadata:
  name: indexhtml
  namespace: schulung
