apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: schulung
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: indexhtml-volume
      mountPath: /usr/share/nginx/html/​
  volumes:
    - name: indexhtml-volume
      configMap:
        name: indexhtml
