apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-neu
  name: nginx-neu
spec:
  initContainers:
  - image: busybox 
    name: busybox
    command: ['sh', '-c', 'touch /data/init.txt && echo "init container was here" > /data/init.txt'] 
    resources: {}
    volumeMounts:
      - name: init-data
        mountPath: /data 
  containers:
  - image: nginx
    name: nginx-neu
    resources: {}
    volumeMounts:
      - name: init-data
        mountPath: /data 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: init-data
      emptyDir: {}