apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-09-27T12:16:58Z"
  labels:
    run: nginx2
  name: nginx2
  namespace: default
  resourceVersion: "17643"
  uid: 1a39cbdf-be15-4154-9d08-e37317e10666
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx-container01
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-nclgd
      readOnly: true
    ports:
      - containerPort: 80
  - image: busybox
    name: busybox-container02
    imagePullPolicy: Always
    command: ['sh', '-c', "sleep 1000000"]
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: kind-control-plane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-nclgd
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-09-27T12:16:58Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-09-27T12:17:00Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-09-27T12:17:00Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-09-27T12:16:58Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://e8136ce1cd64370846c03534f06240cd000524dce07f082651ecadcef04238b8
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:0b970013351304af46f322da1263516b188318682b2ab1091862497591189ff1
    lastState: {}
    name: nginx2
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-09-27T12:17:00Z"
  hostIP: 172.19.0.6
  phase: Running
  podIP: 10.244.0.7
  podIPs:
  - ip: 10.244.0.7
  qosClass: BestEffort
  startTime: "2022-09-27T12:16:58Z"
