apiVersion: v1
kind: Namespace
metadata:
  name: schulung
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webserver
  name: webserver
  namespace: schulung
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
