apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webserver
  name: webserver
  namespace: schulung
spec:
  containers:
    image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
